## -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    module = bld.create_ns3_program('c2-server', ['internet', 'applications'])
    module.source = [
        'model/dynamic-ip-server.cc',
        'helper/dynamic-ip-callback-helper.cc',
    ]

    # header
    headers = bld(features='ns3header')
    headers.module = 'c2-server'
    headers.source = [
        'model/dynamic-ip-server.h',
        'helper/dynamic-ip-callback-helper.h',
    ]

    if (bld.env['ENABLE_EXAMPLES']):
        bld.recurse('examples')

