# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

# def options(opt):
#     pass

# def configure(conf):
#     conf.check_nonfatal(header_name='stdint.h', define_name='HAVE_STDINT_H')

def build(bld):
    module = bld.create_ns3_module('c2-server', ['internet', 'applications', 'network'])
    module.source = [
        'model/dynamic-ip-server.cc',
        'helper/dynamic-ip-callback-helper.cc',
        ]

    module_test = bld.create_ns3_module_test_library('c2-server')
    module_test.source = [
        'test/c2-server-test-suite.cc',
        ]
    # Tests encapsulating example programs should be listed here
    if (bld.env['ENABLE_EXAMPLES']):
        module_test.source.extend([
        #    'test/c2-server-examples-test-suite.cc',
             ])

    headers = bld(features='ns3header')
    headers.module = 'c2-server'
    headers.source = [
        'model/dynamic-ip-server.h',
        'helper/dynamic-ip-callback-helper.h',
        ]

   # if bld.env.ENABLE_EXAMPLES:
   #     bld.recurse('examples')

    # bld.ns3_python_bindings()

